export const datas = [
  {
    name: '电影',
    key: 'movie',
    classifications: [
      {
        key: 'program_classification',
        datas: [
          { name: '全部类型' },
          { name: '论理片' },
          { name: '青春' },
          { name: '生活' },
          { name: '灾难' },
          { name: '歌舞' },
          { name: '文艺' },
          { name: '惊悚' },
          { name: '古装' },
          { name: '励志' },
          { name: '动画' },
          { name: '科幻片' },
          { name: '魔幻' },
          { name: '罪案' },
          { name: '悬疑' },
          { name: '爱情片' },
          { name: '历史' },
          { name: '战争片' },
          { name: '恐怖片' },
          { name: '喜剧片' },
          { name: '动作片' },
          { name: '剧情片' },
          { name: '预告片' }
        ]
      },
      {
        key: 'publish_area',
        datas: [
          { name: '全部地区' },
          { name: '马来西亚' },
          { name: '香港' },
          { name: '韩国' },
          { name: '西班牙' },
          { name: '英国' },
          { name: '美国' },
          { name: '泰国' },
          { name: '法国' },
          { name: '日本' },
          { name: '新加坡' },
          { name: '大陆' },
          { name: '台湾' },
          { name: '印度' },
          { name: '加拿大' },
          { name: '其它' },
          { name: '俄罗斯' }
        ]
      },
      {
        key: 'publish_year',
        datas: [
          { name: '全部年份' },
          { name: '2020' },
          { name: '2019' },
          { name: '2018' },
          { name: '2017' },
          { name: '2016' },
          { name: '2015' },
          { name: '2014' },
          { name: '2013' },
          { name: '2012' },
          { name: '2011' },
          { name: '2010' },
          { name: '2009' },
          { name: '2008' },
          { name: '2007' },
          { name: '2006' },
          { name: '2005' },
          { name: '2004' },
          { name: '2003' },
          { name: '2002' },
          { name: '2001' },
          { name: '2000' },
          { name: '1999' },
          { name: '1998' },
          { name: '1997' },
          { name: '1996' },
          { name: '1995' },
          { name: '1994' },
          { name: '1993' },
          { name: '1992' },
          { name: '1991' },
          { name: '1990' },
          { name: '1989' },
          { name: '1988' },
          { name: '1987' },
          { name: '1986' },
          { name: '1985' },
          { name: '1984' },
          { name: '1983' },
          { name: '1982' },
          { name: '1981' },
          { name: '1980' },
          { name: '1979' },
          { name: '1978' },
          { name: '1977' },
          { name: '1976' },
          { name: '1975' },
          { name: '1974' },
          { name: '1973' },
          { name: '1972' },
          { name: '1971' },
          { name: '1970' },
          { name: '1969' },
          { name: '1968' },
          { name: '1967' },
          { name: '1966' },
          { name: '1965' },
          { name: '1964' },
          { name: '1963' },
          { name: '1962' },
          { name: '1961' },
          { name: '1960' },
          { name: '1959' },
          { name: '1958' },
          { name: '1957' },
          { name: '1956' },
          { name: '1955' },
          { name: '1954' },
          { name: '1953' },
          { name: '1952' },
          { name: '1951' },
          { name: '1950' },
          { name: '1949' },
          { name: '1948' },
          { name: '1947' },
          { name: '1946' },
          { name: '1945' },
          { name: '1944' },
          { name: '1943' },
          { name: '1942' },
          { name: '1941' },
          { name: '1940' },
          { name: '1939' },
          { name: '1938' },
          { name: '1937' },
          { name: '1936' },
          { name: '1935' },
          { name: '1934' },
          { name: '1933' },
          { name: '1932' },
          { name: '1931' },
          { name: '1930' },
          { name: '1929' },
          { name: '1928' },
          { name: '1927' },
          { name: '1926' },
          { name: '1925' },
          { name: '1924' },
          { name: '1923' },
          { name: '1922' },
          { name: '1921' },
          { name: '1920' },
          { name: '1917' },
          { name: '1916' },
          { name: '1915' },
          { name: '1905' },
          { name: '1903' },
          { name: '1902' }
        ]
      }
    ]
  },
  {
    name: '电视剧',
    key: 'tv_play',
    classifications: [
      {
        key: 'program_classification',
        datas: [
          { name: '全部类型' },
          { name: '香港剧' },
          { name: '历史' },
          { name: '韩国剧' },
          { name: '武侠' },
          { name: '悬疑' },
          { name: '喜剧' },
          { name: '美国剧' },
          { name: '穿越' },
          { name: '海外剧' },
          { name: '生活' },
          { name: '偶像' },
          { name: '泰国剧' },
          { name: '日本剧' },
          { name: '国产剧' },
          { name: '古装' },
          { name: '台湾剧' }
        ]
      },
      {
        key: 'publish_area',
        datas: [
          { name: '全部地区' },
          { name: '香港' },
          { name: '韩国' },
          { name: '西班牙' },
          { name: '英国' },
          { name: '美国' },
          { name: '泰国' },
          { name: '法国' },
          { name: '日本' },
          { name: '新加坡' },
          { name: '大陆' },
          { name: '台湾' },
          { name: '印度' },
          { name: '加拿大' },
          { name: '其它' },
          { name: '俄罗斯' }
        ]
      },
      {
        key: 'publish_year',
        datas: [
          { name: '全部年份' },
          { name: '2020' },
          { name: '2019' },
          { name: '2018' },
          { name: '2017' },
          { name: '2016' },
          { name: '2015' },
          { name: '2014' },
          { name: '2013' },
          { name: '2012' },
          { name: '2011' },
          { name: '2010' },
          { name: '2009' },
          { name: '2008' },
          { name: '2007' },
          { name: '2006' },
          { name: '2005' },
          { name: '2004' },
          { name: '2003' },
          { name: '2002' },
          { name: '2001' },
          { name: '2000' },
          { name: '1999' },
          { name: '1998' },
          { name: '1997' },
          { name: '1996' },
          { name: '1995' },
          { name: '1994' },
          { name: '1993' },
          { name: '1992' },
          { name: '1991' },
          { name: '1990' },
          { name: '1989' },
          { name: '1988' },
          { name: '1987' },
          { name: '1986' },
          { name: '1985' },
          { name: '1984' },
          { name: '1983' },
          { name: '1982' },
          { name: '1980' },
          { name: '1978' },
          { name: '1977' },
          { name: '1976' },
          { name: '1969' },
          { name: '1963' },
          { name: '1960' },
          { name: '1957' },
          { name: '1956' }
        ]
      }
    ]
  },
  {
    name: '综艺',
    key: 'variety_show',
    classifications: [
      {
        key: 'program_classification',
        datas: [
          { name: '全部类型' },
          { name: '综艺' },
          { name: '音乐' },
          { name: '财经' },
          { name: '脱口秀' },
          { name: '真人秀' },
          { name: '晚会' },
          { name: '时尚' }
        ]
      },
      {
        key: 'publish_area',
        datas: [
          { name: '全部地区' },
          { name: '马来西亚' },
          { name: '香港' },
          { name: '韩国' },
          { name: '西班牙' },
          { name: '英国' },
          { name: '美国' },
          { name: '日本' },
          { name: '大陆' },
          { name: '台湾' },
          { name: '其它' },
          { name: '俄罗斯' }
        ]
      },
      {
        key: 'publish_year',
        datas: [
          { name: '全部年份' },
          { name: '2020' },
          { name: '2019' },
          { name: '2018' },
          { name: '2017' },
          { name: '2016' },
          { name: '2015' },
          { name: '2014' },
          { name: '2013' },
          { name: '2012' },
          { name: '2011' },
          { name: '2010' },
          { name: '2009' },
          { name: '2008' },
          { name: '2007' },
          { name: '2006' },
          { name: '2005' },
          { name: '2002' },
          { name: '2001' },
          { name: '2000' },
          { name: '1999' },
          { name: '1993' },
          { name: '1965' },
          { name: '1964' }
        ]
      }
    ]
  },
  {
    name: '动漫',
    key: 'comic',
    classifications: [
      {
        key: 'program_classification',
        datas: [
          { name: '全部类型' },
          { name: '动漫' },
          { name: '经典' },
          { name: '童话' },
          { name: '竞技' },
          { name: '搞笑' },
          { name: '少女' }
        ]
      },
      {
        key: 'publish_area',
        datas: [
          { name: '全部地区' },
          { name: '马来西亚' },
          { name: '香港' },
          { name: '韩国' },
          { name: '西班牙' },
          { name: '英国' },
          { name: '美国' },
          { name: '泰国' },
          { name: '法国' },
          { name: '日本' },
          { name: '大陆' },
          { name: '台湾' },
          { name: '印度' },
          { name: '加拿大' },
          { name: '其它' },
          { name: '俄罗斯' }
        ]
      },
      {
        key: 'publish_year',
        datas: [
          { name: '全部年份' },
          { name: '2020' },
          { name: '2019' },
          { name: '2018' },
          { name: '2017' },
          { name: '2016' },
          { name: '2015' },
          { name: '2014' },
          { name: '2013' },
          { name: '2012' },
          { name: '2011' },
          { name: '2010' },
          { name: '2009' },
          { name: '2008' },
          { name: '2007' },
          { name: '2006' },
          { name: '2005' },
          { name: '2004' },
          { name: '2003' },
          { name: '2002' },
          { name: '2001' },
          { name: '2000' },
          { name: '1999' },
          { name: '1998' },
          { name: '1997' },
          { name: '1996' },
          { name: '1995' },
          { name: '1994' },
          { name: '1993' },
          { name: '1992' },
          { name: '1991' },
          { name: '1990' },
          { name: '1989' },
          { name: '1988' },
          { name: '1987' },
          { name: '1986' },
          { name: '1985' },
          { name: '1984' },
          { name: '1983' },
          { name: '1982' },
          { name: '1981' },
          { name: '1980' },
          { name: '1979' },
          { name: '1978' },
          { name: '1977' },
          { name: '1975' },
          { name: '1974' },
          { name: '1973' },
          { name: '1971' },
          { name: '1970' },
          { name: '1968' },
          { name: '1967' },
          { name: '1965' },
          { name: '1964' },
          { name: '1963' },
          { name: '1962' },
          { name: '1961' },
          { name: '1959' },
          { name: '1958' },
          { name: '1957' },
          { name: '1956' },
          { name: '1955' },
          { name: '1951' },
          { name: '1948' },
          { name: '1943' },
          { name: '1941' },
          { name: '1940' },
          { name: '1939' },
          { name: '1938' },
          { name: '1937' },
          { name: '1935' },
          { name: '1933' }
        ]
      }
    ]
  }
];
